import json
import os
import re
from urllib.parse import urlparse, parse_qs

from tennis_elo.config import ROOT_DIR, CONFIG_DIR
from tennis_elo.utils import now_iso, save_json, save_text, clean_str


INPUT_FILE = ROOT_DIR / "data" / "input" / "matches_today.json"
OUTPUT_URLS_FILE = CONFIG_DIR / "flashscore_urls.txt"
REPORT_FILE = ROOT_DIR / "data" / "reports" / "generated_history_urls_report.json"

# Start conservative. You can raise this later.
MAX_MATCHES = int(os.getenv("MAX_HISTORY_MATCHES", "20"))

# For Rezultati.com these are known-good from our test.
REZULTATI_SURFACE_SLUGS = [
    "sve-podloge",
    "zemlja",
    "tvrda-podloga",
    "trava",
]

# For Flashscore.com we keep this for later compatibility.
# The current proven parser is Rezultati/omjer format.
FLASHSCORE_H2H_SLUGS = [
    "overall",
    "clay",
    "hard",
    "grass",
]


def load_json(path, default):
    if not os.path.exists(path):
        return default

    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return default


def rows_from_payload(payload):
    if isinstance(payload, list):
        return payload

    if isinstance(payload, dict):
        for key in ["matches", "rows", "data", "results", "picks", "decisions"]:
            value = payload.get(key)
            if isinstance(value, list):
                return value

    return []


def extract_mid(url):
    url = clean_str(url)

    if not url:
        return ""

    parsed = urlparse(url)
    qs = parse_qs(parsed.query)

    if "mid" in qs and qs["mid"]:
        return qs["mid"][0]

    m = re.search(r"[?&]mid=([^&#/]+)", url)
    if m:
        return m.group(1)

    return ""


def strip_after_mid_path(url):
    """
    Rezultati match URL examples:
    https://www.rezultati.com/utakmica/tenis/legout-timo-.../walton-adam-.../?mid=j5dT0o54
    https://www.rezultati.com/utakmica/tenis/legout-timo-.../walton-adam-.../omjer/sve-podloge/?mid=j5dT0o54

    We want base:
    https://www.rezultati.com/utakmica/tenis/legout-timo-.../walton-adam-...
    """
    url = clean_str(url)
    if not url:
        return ""

    url = url.split("#", 1)[0]
    url = url.split("?", 1)[0]
    url = url.rstrip("/")

    # Remove existing h2h/omjer suffix if present.
    marker = "/omjer/"
    if marker in url:
        url = url.split(marker, 1)[0].rstrip("/")

    return url


def make_rezultati_history_urls(match_url):
    mid = extract_mid(match_url)
    base = strip_after_mid_path(match_url)

    if not base or not mid:
        return []

    return [
        f"{base}/omjer/{slug}/?mid={mid}"
        for slug in REZULTATI_SURFACE_SLUGS
    ]


def make_flashscore_history_urls(match_url):
    """
    Kept for future. Main tested flow is rezultati.com.

    Flashscore pages usually use hash routes:
    .../?mid=abc#/h2h/overall
    """
    mid = extract_mid(match_url)
    base = strip_after_mid_path(match_url)

    if not base or not mid:
        return []

    return [
        f"{base}/?mid={mid}#/h2h/{slug}"
        for slug in FLASHSCORE_H2H_SLUGS
    ]


def get_url_from_row(row):
    if not isinstance(row, dict):
        return clean_str(row)

    for key in [
        "match_url",
        "url",
        "source_match_url",
        "flashscore_match_url",
        "rezultati_match_url",
        "odds_url",
    ]:
        value = clean_str(row.get(key))
        if value and ("rezultati.com" in value or "flashscore.com" in value):
            return value

    # source_url in Tennis Machine is sometimes just homepage, avoid that unless it is real match URL.
    value = clean_str(row.get("source_url"))
    if value and ("/utakmica/tenis/" in value or "/match/tennis/" in value):
        return value

    return ""


def make_history_urls(match_url):
    url = clean_str(match_url)

    if not url:
        return []

    if "rezultati.com" in url:
        return make_rezultati_history_urls(url)

    if "flashscore.com" in url:
        return make_flashscore_history_urls(url)

    return []


def build_comment_header():
    return "\n".join([
        "# Auto-generated by tennis_elo.sources.generate_history_urls",
        "# Do not edit manually if you run this generator again.",
        "# One URL per line.",
        "",
    ])


def main():
    payload = load_json(INPUT_FILE, {})
    rows = rows_from_payload(payload)

    generated = []
    skipped = []
    seen = set()
    matches_used = 0

    for row in rows:
        if matches_used >= MAX_MATCHES:
            break

        match_url = get_url_from_row(row)

        if not match_url:
            skipped.append({
                "reason": "missing_match_url",
                "match": row.get("match") if isinstance(row, dict) else "",
                "row": row,
            })
            continue

        urls = make_history_urls(match_url)

        if not urls:
            skipped.append({
                "reason": "could_not_generate_history_urls",
                "match_url": match_url,
                "match": row.get("match") if isinstance(row, dict) else "",
            })
            continue

        matches_used += 1

        for url in urls:
            if url in seen:
                continue

            seen.add(url)

            generated.append({
                "history_url": url,
                "match_url": match_url,
                "match": row.get("match") if isinstance(row, dict) else "",
                "player_1": row.get("player_1") if isinstance(row, dict) else "",
                "player_2": row.get("player_2") if isinstance(row, dict) else "",
                "date": row.get("date") if isinstance(row, dict) else "",
                "status": row.get("status") if isinstance(row, dict) else "",
                "tournament": row.get("tournament") if isinstance(row, dict) else "",
            })

    url_lines = [item["history_url"] for item in generated]
    text = build_comment_header() + "\n".join(url_lines) + "\n"

    save_text(OUTPUT_URLS_FILE, text)

    report = {
        "generated_at": now_iso(),
        "input_file": str(INPUT_FILE),
        "output_file": str(OUTPUT_URLS_FILE),
        "settings": {
            "max_matches": MAX_MATCHES,
            "urls_per_match": 4,
        },
        "counts": {
            "input_rows": len(rows),
            "matches_used": matches_used,
            "history_urls_generated": len(generated),
            "skipped": len(skipped),
        },
        "generated": generated,
        "skipped": skipped[:200],
    }

    save_json(REPORT_FILE, report)

    print("")
    print("GENERATE HISTORY URLS DONE")
    print(report["counts"])
    print(f"Input:  {INPUT_FILE}")
    print(f"Output: {OUTPUT_URLS_FILE}")
    print(f"Report: {REPORT_FILE}")
    print("")


if __name__ == "__main__":
    main()
